name: generic-python
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-pacman
  - r-devtools
  - r-janitor
  - r-cowplot
  - r-ggbeeswarm
  - r-patchwork
  - r-viridis
  - r-ggridges
  - r-ggnewscale
  - r-magrittr
  - r-zeallot
  - r-openxlsx
  - r-igraph

  - pytest
  - ipykernel
  - numpy
  - ipywidgets
  - pandas
  - statsmodels
  - ipython
  - pandoc
  - pyarrow
  - jupytext
  - black
  - jupyterlab
  - pip
  - nltk
  - python=3.12
  - scanpy
  - tqdm
  - h5py
  - scikit-learn
  - nodejs
  - matplotlib
  - pysam
  - pyyaml
  - scipy
  - regex
  - ruff
  - anndata
  - biopython
  - seaborn
# prefix: /Users/canderson/miniconda3/envs/generic-python
